### ISSUE TITLE
Доработка модалок

### ISSUE THREAD

**Issue by arrayumi** [Marketplace-of-telegram-bots-for-retail/frontend#117]
Хорошо бы добавить роутинг модальных окон авторизации и регистрации, если нужны материалы как это реализовать напишите в личку в телеграмм @max_orel. Это как пожелание. Нужно это чтобы при нажатии на F5 не слетало модальное окно авторизации и регистрации. Также слетают состояния формы регистрации, его тоже хорошо бы между этапами сохранять

_Originally posted by @MaxOrel in https://github.com/Marketplace-of-telegram-bots-for-retail/frontend/issues/76#issuecomment-1766286541_

**Comment by arrayumi** [comment]
- [ ] сохранение состояний форм регистрации между этапами
- [ ] разобраться в роутинге

**Comment by arrayumi** [comment]
https://dev.to/unorthodev/how-to-make-routable-modals-in-react-with-react-router-3hgp
нашла статью по теме, чтобы закрыть последнюю задачу надо прочитать

**Comment by MaxOrel** [comment]
Видео по роутингу скинул Дмитрию

**Comment by MaxOrel** [comment]
@TokmakDA (https://t.me/TokmakDA)
