### ISSUE TITLE
Доработка личного кабинета

### ISSUE THREAD

**Issue by AlexandraSmirnova7** [Marketplace-of-telegram-bots-for-retail/frontend#18]
- [x] создать попап редактирования/удаления фото

- [x] добавить стили

- [x] добавить валидацию полей

- [x] реализовать функциональности:

- [x] удаления пользователя 

- [x] изменения данных пользователя

- [x] изменение фото пользователя 

- [x] изменение пароля

- [x] выход позбзователя из системы

- [x] опционально : оптимизировать код, разбить на компоненты

- [ ] удаление фото
- [x] рефакторинг спан инпута
- [x] подтверждение выхода из профиля
- [x] раскрытие полей изменения пароля

**Comment by arrayumi** [comment]
- [ ]  обновить верстку по новому дизайну

**Comment by arrayumi** [comment]
задача доработки удаления фото заведена в багрепорте
