### ISSUE TITLE
Доработка страницы товара + ревью

### ISSUE THREAD

**Issue by AlexandraSmirnova7** [Marketplace-of-telegram-bots-for-retail/frontend#21]
- [x] написать запрос к api для получения отзывов
- [x] отобразить полученные данные от api на странице продукта в разделе отзывы
- [x] написать запрос к api для создания отзыва
- [x] протестировать создание отзыва
- [x] добавить на страницу универсальный компонент рейтинга
- [x] добавить на страницу универсальный компонент "добавить в избранное"
- [x] добавить на страницу универсальный компонент кнопки "в корзину"
- [x] ограничить количество выводимых отзывом 3, остальные показывать после нажатия кнопки Показать все.
- [x] сделать изменение содержимого рейтинга при наведении в ProductInfo

**Comment by TokmakDA** [comment]
в процессе
