### ISSUE TITLE
Доработка: страница ошибок, избранное, главная страница

### ISSUE THREAD

**Issue by AlexandraSmirnova7** [Marketplace-of-telegram-bots-for-retail/frontend#64]

**Comment by TokmakDA** [comment]
- [ ] [Доработка главной страницы #68
](https://github.com/Marketplace-of-telegram-bots-for-retail/frontend/issues/68)
- [ ] [](https://github.com/orgs/Marketplace-of-telegram-bots-for-retail/projects/1/views/1?pane=issue&itemId=41315545)
- [ ] [](url)
- [ ] [](url)
- [ ] [](url)
- [ ]
